### ISSUE TITLE
Does filelocksmith *require* cc 1.1?

### ISSUE THREAD

**Issue by jsgf** [velopack/filelocksmith-rs#3]
We're having a problem where filelocksmith's "1.1" requirement for `cc` is conflicting with tree-sitter 0.20's "^1.0" requirement for it.

(This is fixed in later versions of tree-sitter, but unfortunately we're pinned to 0.20 because of a bunch of other things depending on the older tree-sitter which haven't been ported to newer versions yet.)

The simple workaround is to make filelocksmith use `cc = "1"`. This appears to work locally, but it's not clear to me whether there's some specific reason it has the 1.1 requirement. Would it be OK to make it a looser constraint?

**Comment by caesay** [comment]
I'm fairly new to rust, there's no reason for requiring 1.1 other than to keep dependencies updated. If tree-sitter is requiring "^1.0", shouldn't things just work? I'd assume that tree-sitter would be happy with 1.1 in that case. 

My understanding is `cc = "1"` is equivelant to `cc = "^1.0"`, is that correct? and both of these are happy with basically anything `1.x.x`.

**Comment by caesay** [comment]
But also, feel free to send a PR. I don't mind.

**Comment by caesay** [comment]
Changed and published
